name: Automated Commit

on:
  push:
    branches: [master]

  schedule:
    # Randomize cronjob 
    - cron: '*/60 * * * *' # Setiap 60 menit
    - cron: '15,45 * * * *' # Pada menit ke-15 dan 45 setiap jam
    - cron: '0 */3 * * *' # Setiap 3 jam sekali

  workflow_dispatch:

permissions:
  contents: write

jobs:
  update_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Generate Random Delay
        run: |
          # Menghasilkan waktu tunda acak antara 0-360 detik (0-6 Menit)
          random_delay=$(( RANDOM % 360 ))
          echo "Waiting for $random_delay seconds"
          sleep $random_delay

      - name: Update Timestamp File
        run: |
          current_time=$(date '+%Y-%m-%d %H:%M:%S')
          echo "Updated on $current_time" > TIMESTAMP.txt

      - name: Setup Git Configuration
        run: |
          git config user.email "69198533+justTheKai@users.noreply.github.com"
          git config user.name "JustThekai"

      - name: Prepare Commit
        run: |
          commit_messages=(
            "Just keeping things fresh 👋"
            "Quick system check-in ✅"
            "Routine maintenance complete 🛠️"
            "Keeping the lights on 💡"
            "Another day, another update 🌞"
            "Dropping by to say hello to the repo 👋"
            "Maintenance mode: activated ⚙️"
            "Smooth sailing ahead 🚢"
            "Sync and shine ✨"
            "Repo health check: all good! 💪"
            "Timestamp updated, systems nominal 🖥️"
            "Checking in, everything's looking great 🌈"
            "Minor behind-the-scenes magic ✨"
            "Just a friendly automated nudge 🤖"
            "Keeping things running smoothly 🏃"
          )
          random_msg=${commit_messages[$RANDOM % ${#commit_messages[@]}]}

          git add TIMESTAMP.txt
          git commit -m "$random_msg - $current_time" || echo "No changes to commit."

      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          directory: '.'
          github_token: ${{ secrets.GITHUB_TOKEN }}
